version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    container_name: elasticsearch
    environment: 
     - xpack.security.enabled=false
    ports:
     - "9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.3
    ports:
     - "5044:5044"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    ports:
     - "5601:5601" 
  